.RECIPEPREFIX := >

.PHONY: up down config

up:
>docker compose -f docker-compose.yml up --build

down:
>docker compose -f docker-compose.yml down

config:
>docker compose -f docker-compose.yml config
